### ISSUE TITLE
missing almasb-lib 1.1.6 jar file

### ISSUE THREAD

**Issue by telostia** [AlmasB/mmorpg#82]
hi,
 Was just testing out this project when I ran into a problem with missing jar file from the maven repo(local). I tried finding it at the online repo but could not locate. Would you be kind enough to do a commit or direct me to the 1.1.6 jar file ? Thanks.

**Comment by AlmasB** [comment]
Hi,
have now committed it. Please note that I'm not aware of the state the project is in. Though last time I checked it seemed to run.

**Comment by telostia** [comment]
Hi,
 Game works good :). Do you intend to release the almasB lib publicly? I would like to use it for the purpose of learning Java client server programming myself. The concept of your coding seems quite good. Thanks for sharing!

**Comment by AlmasB** [comment]
That lib was just an old collection of code snippets I used. Some of it (including "net" package) has been improved and incorporated into a game library - https://github.com/AlmasB/FXGL I'd recommend using that instead

**Comment by telostia** [comment]
Ok cool. thanks
